METHOD_KNOWLEDGE = {
    "ols": {
        "display_name": "Robust OLS",
        "absorbed_from_original_tools": ["ordinary_least_square_regression"],
        "when_to_use": "Use for baseline associative models or treatment-effect regressions when endogeneity and panel structure are not the dominant design problem.",
        "core_rule": "Fallback baseline when no stronger panel, IV, or policy-shock design is clearly specified.",
        "required_inputs": ["outcome", "treatment", "optional controls"],
        "identification_logic": "Interpret the treatment coefficient as a conditional association unless the design gives stronger causal leverage.",
        "diagnostics_to_check": ["treatment coefficient precision", "constant or collinear regressors", "omitted-variable risk"],
        "common_failure_modes": ["using OLS despite endogeneity", "overstating causal claims from descriptive models"],
    },
    "fe": {
        "display_name": "Two-Way Fixed Effects",
        "absorbed_from_original_tools": ["Staggered_Diff_in_Diff_regression", "PanelOLS usage across panel tools"],
        "when_to_use": "Use for panel data where identification relies on within-unit variation after absorbing entity and time shocks.",
        "core_rule": "If the data are panel and the task is not clearly IV, DID, or event study, default to FE rather than pooled OLS.",
        "required_inputs": ["outcome", "treatment", "entity_id", "time_id", "optional controls"],
        "identification_logic": "Use within-entity treatment changes while differencing out unit and calendar-time confounders.",
        "diagnostics_to_check": ["within-unit treatment variation", "absorbed regressors", "identification after FE"],
        "common_failure_modes": ["no within-unit variation", "assuming FE solves endogeneity automatically"],
    },
    "iv": {
        "display_name": "IV-2SLS",
        "absorbed_from_original_tools": ["IV_2SLS_regression", "IV_2SLS_IV_setting_test"],
        "when_to_use": "Use when treatment is endogenous and a credible external instrument is available.",
        "core_rule": "If an instrument is provided or the query explicitly mentions IV / endogeneity, route to IV before FE or OLS.",
        "required_inputs": ["outcome", "treatment", "instrument", "optional controls"],
        "identification_logic": "Use only the treatment variation induced by the instrument, not the full endogenous treatment variation.",
        "diagnostics_to_check": ["first-stage relevance", "weak instrument risk", "exclusion restriction plausibility"],
        "common_failure_modes": ["weak instruments", "bad instruments that directly affect the outcome"],
    },
    "did": {
        "display_name": "Difference-in-Differences",
        "absorbed_from_original_tools": ["Static_Diff_in_Diff_regression", "Staggered_Diff_in_Diff_regression"],
        "when_to_use": "Use for policy shocks or treatment timing designs where treated and control units are compared before and after adoption.",
        "core_rule": "If the query is about a policy effect or treatment timing and the data provide group-post or staggered treatment timing, prefer DID over generic FE.",
        "required_inputs": ["outcome", "group-post or panel treatment indicator", "entity_id + time_id recommended"],
        "identification_logic": "Compare changes over time for treated units against changes for control units under a parallel-trends assumption.",
        "diagnostics_to_check": ["parallel-trends plausibility", "treatment timing variation", "binary treatment design"],
        "common_failure_modes": ["no real control group", "non-binary treatment timing", "causal claims without design checks"],
    },
    "event-study": {
        "display_name": "Staggered DID Event Study",
        "absorbed_from_original_tools": ["Staggered_Diff_in_Diff_Event_Study_regression"],
        "when_to_use": "Use when the user wants dynamic treatment effects, pre-trend checks, or lead-lag coefficients around staggered adoption.",
        "core_rule": "If the query asks for event-study dynamics or pre-trend diagnostics in panel data with treatment timing, route here before plain DID.",
        "required_inputs": ["outcome", "binary treatment indicator", "entity_id", "time_id", "optional controls"],
        "identification_logic": "Estimate dynamic lead and lag coefficients around first treatment adoption while absorbing entity and time effects.",
        "diagnostics_to_check": ["significant pre-treatment leads", "always-treated units", "coherent treatment timing"],
        "common_failure_modes": ["always-treated units", "treatment that turns on and off repeatedly", "over-interpreting noisy pre-trends"],
    },
}
