METHOD_KNOWLEDGE = {
    "ols": {
        "display_name": "Robust OLS",
        "absorbed_from_original_tools": ["ordinary_least_square_regression"],
        "when_to_use": "Use for baseline associative models or treatment-effect regressions when endogeneity and panel structure are not the dominant design problem.",
        "core_rule": "Fallback baseline when no stronger panel, IV, or policy-shock design is clearly specified.",
        "required_inputs": ["outcome", "treatment", "optional controls"],
        "identification_logic": "Interpret the treatment coefficient as a conditional association unless the design gives stronger causal leverage.",
        "diagnostics_to_check": ["treatment coefficient precision", "constant or collinear regressors", "omitted-variable risk"],
        "common_failure_modes": ["using OLS despite endogeneity", "overstating causal claims from descriptive models"],
    },
    "fe": {
        "display_name": "Two-Way Fixed Effects",
        "absorbed_from_original_tools": ["Staggered_Diff_in_Diff_regression", "PanelOLS usage across panel tools"],
        "when_to_use": "Use for panel data where identification relies on within-unit variation after absorbing entity and time shocks.",
        "core_rule": "If the data are panel and the task is not clearly IV, DID, or event study, default to FE rather than pooled OLS.",
        "required_inputs": ["outcome", "treatment", "entity_id", "time_id", "optional controls"],
        "identification_logic": "Use within-entity treatment changes while differencing out unit and calendar-time confounders.",
        "diagnostics_to_check": ["within-unit treatment variation", "absorbed regressors", "identification after FE"],
        "common_failure_modes": ["no within-unit variation", "assuming FE solves endogeneity automatically"],
    },
    "iv": {
        "display_name": "IV-2SLS",
        "absorbed_from_original_tools": ["IV_2SLS_regression", "IV_2SLS_IV_setting_test"],
        "when_to_use": "Use when treatment is endogenous and a credible external instrument is available.",
        "core_rule": "If an instrument is provided or the query explicitly mentions IV / endogeneity, route to IV before FE or OLS.",
        "required_inputs": ["outcome", "treatment", "instrument", "optional controls"],
        "identification_logic": "Use only the treatment variation induced by the instrument, not the full endogenous treatment variation.",
        "diagnostics_to_check": ["first-stage relevance", "weak instrument risk", "exclusion restriction plausibility"],
        "common_failure_modes": ["weak instruments", "bad instruments that directly affect the outcome"],
    },
    "did": {
        "display_name": "Difference-in-Differences",
        "absorbed_from_original_tools": ["Static_Diff_in_Diff_regression", "Staggered_Diff_in_Diff_regression"],
        "when_to_use": "Use for policy shocks or treatment timing designs where treated and control units are compared before and after adoption.",
        "core_rule": "If the query is about a policy effect or treatment timing and the data provide group-post or staggered treatment timing, prefer DID over generic FE.",
        "required_inputs": ["outcome", "group-post or panel treatment indicator", "entity_id + time_id recommended"],
        "identification_logic": "Compare changes over time for treated units against changes for control units under a parallel-trends assumption.",
        "diagnostics_to_check": ["parallel-trends plausibility", "treatment timing variation", "binary treatment design"],
        "common_failure_modes": ["no real control group", "non-binary treatment timing", "causal claims without design checks"],
    },
    "event-study": {
        "display_name": "Staggered DID Event Study",
        "absorbed_from_original_tools": ["Staggered_Diff_in_Diff_Event_Study_regression"],
        "when_to_use": "Use when the user wants dynamic treatment effects, pre-trend checks, or lead-lag coefficients around staggered adoption.",
        "core_rule": "If the query asks for event-study dynamics or pre-trend diagnostics in panel data with treatment timing, route here before plain DID.",
        "required_inputs": ["outcome", "binary treatment indicator", "entity_id", "time_id", "optional controls"],
        "identification_logic": "Estimate dynamic lead and lag coefficients around first treatment adoption while absorbing entity and time effects.",
        "diagnostics_to_check": ["significant pre-treatment leads", "always-treated units", "coherent treatment timing"],
        "common_failure_modes": ["always-treated units", "treatment that turns on and off repeatedly", "over-interpreting noisy pre-trends"],
    },
    "rdd": {
        "display_name": "Sharp RDD",
        "absorbed_from_original_tools": ["Sharp_Regression_Discontinuity_Design_regression"],
        "when_to_use": "Use when treatment assignment changes discontinuously at a known cutoff in a running variable.",
        "core_rule": "If the query mentions a cutoff / threshold / discontinuity and a running variable plus cutoff are provided, route to sharp RDD.",
        "required_inputs": ["outcome", "treatment", "running_variable", "cutoff", "optional controls"],
        "identification_logic": "Compare observations just above and below the cutoff under continuity of potential outcomes at the threshold.",
        "diagnostics_to_check": ["support on both sides of the cutoff", "bandwidth or polynomial sensitivity", "whether treatment jumps sharply at the threshold"],
        "common_failure_modes": ["cutoff outside support", "fuzzy treatment despite sharp RDD specification", "too-wide bandwidth driving global functional-form bias"],
    },
    "psm": {
        "display_name": "Propensity Score Matching",
        "absorbed_from_original_tools": ["propensity_score_construction", "propensity_score_matching"],
        "when_to_use": "Use when treatment is binary and selection on observables is plausible, especially when the user explicitly asks for matching.",
        "core_rule": "If the query asks for matching or PSM and the treatment is binary, route here before plain OLS.",
        "required_inputs": ["outcome", "binary treatment", "covariates for the propensity model"],
        "identification_logic": "Reweight the sample by matching treated and control observations with similar estimated treatment propensity.",
        "diagnostics_to_check": ["overlap in propensity scores", "balance intuition", "sensitivity to matched neighbor count"],
        "common_failure_modes": ["poor overlap", "using PSM without credible observables", "treating matching estimates as immune to hidden bias"],
    },
    "ipw": {
        "display_name": "Inverse Probability Weighting",
        "absorbed_from_original_tools": ["propensity_score_construction", "propensity_score_inverse_probability_weighting"],
        "when_to_use": "Use when treatment is binary and the user wants weighting based on estimated treatment probabilities rather than nearest-neighbor matching.",
        "core_rule": "If the query asks for IPW / weighting from propensity scores and the treatment is binary, route here.",
        "required_inputs": ["outcome", "binary treatment", "covariates for the propensity model"],
        "identification_logic": "Estimate treatment probabilities and weight observations by the inverse of the treatment they received.",
        "diagnostics_to_check": ["extreme propensity scores", "effective weight stability", "common support"],
        "common_failure_modes": ["extreme weights", "positivity violations", "using IPW with a badly misspecified propensity model"],
    },
    "aipw": {
        "display_name": "Augmented IPW",
        "absorbed_from_original_tools": ["propensity_score_double_robust_estimator_augmented_IPW"],
        "when_to_use": "Use when treatment is binary and the user wants a doubly robust estimator that combines an outcome model with inverse-probability weighting.",
        "core_rule": "If the query asks for AIPW, augmented IPW, or doubly robust estimation with binary treatment, route here before plain IPW.",
        "required_inputs": ["outcome", "binary treatment", "covariates for propensity and outcome models"],
        "identification_logic": "Combine treatment-probability weighting with separate outcome regressions so consistency can survive one model being misspecified.",
        "diagnostics_to_check": ["common support", "extreme weights", "balance after weighting", "dependence on outcome-model functional form"],
        "common_failure_modes": ["poor overlap", "joint misspecification of propensity and outcome models", "treating doubly robust as assumption-free"],
    },
    "ipwra": {
        "display_name": "IPW Regression Adjustment",
        "absorbed_from_original_tools": ["propensity_score_double_robust_estimator_IPW_regression_adjustment"],
        "when_to_use": "Use when treatment is binary and the user wants a doubly robust weighted regression-adjustment estimator rather than AIPW's augmentation formula.",
        "core_rule": "If the query asks for IPWRA or doubly robust regression adjustment with binary treatment, route here.",
        "required_inputs": ["outcome", "binary treatment", "covariates for propensity and outcome models"],
        "identification_logic": "Estimate treatment propensity, construct inverse-probability weights, and run a weighted regression adjustment model for the outcome.",
        "diagnostics_to_check": ["common support", "extreme weights", "balance after weighting", "sensitivity to regression specification"],
        "common_failure_modes": ["poor overlap", "joint misspecification of weighting and outcome models", "reading weighted regression adjustment as assumption-free"],
    },
    "fuzzy-rdd": {
        "display_name": "Fuzzy RDD",
        "absorbed_from_original_tools": ["Fuzzy_Regression_Discontinuity_Design_regression"],
        "when_to_use": "Use when cutoff assignment shifts treatment probability but does not deterministically assign treatment.",
        "core_rule": "If the query explicitly mentions fuzzy RDD and running-variable / cutoff inputs are available, route here instead of sharp RDD.",
        "required_inputs": ["outcome", "treatment", "running_variable", "cutoff", "optional controls"],
        "identification_logic": "Use crossing the cutoff as an instrument for treatment within a local bandwidth around the threshold.",
        "diagnostics_to_check": ["support near cutoff", "first-stage jump in treatment probability", "bandwidth or polynomial sensitivity"],
        "common_failure_modes": ["weak first stage at the cutoff", "using fuzzy RDD when treatment is actually sharp", "interpreting global patterns as local treatment effects"],
    },
}
